name: Demo Deploy Stanza Database Scripts
on:
  workflow_dispatch:
      inputs:
        environment:
            description: Environment to deploy to
            required: true
            type: environment
        dbName:
          description: 'Select the database folder to deploy'
          required: true
          type: choice
          options:
            - None
            - Committee
            - Identity
          default: None
permissions: read-all  

jobs:
  print-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Print input and env variables
        run: |
          DB_USER: ${{ vars.DBUSERNAME }}
          DB_HOST: ${{ vars.SERVERNAME }}
          DB_PASSWORD: ${{ vars.DBPASSWORD }}
          echo "==============================="
          echo "DB Folder Name: ${{ github.event.inputs.dbName }}"
          echo "DB_USER: $DB_USER"
          echo "DB_HOST: $DB_HOST"
          echo "DB_PASSWORD: $DB_PASSWORD"
          echo "==============================="
