name: Demo Deploy Stanza Database Scripts
on:
  workflow_dispatch:
      inputs:
        environment:
            description: Environment to deploy to
            required: true
            type: environment
        dbName:
          description: 'Select the database folder to deploy'
          required: true
          type: choice
          options:
            - None
            - Committee
            - Identity
          default: None
permissions: read-all  

jobs:
  DB_Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute database scripts filtered by DB folder name
        env:
          DB_NAME_INPUT: ${{ github.event.inputs.dbName }}
          DB_USER: ${{ vars.DBUSERNAME }}
          DB_HOST: ${{ vars.SERVERNAME }}
          DB_Password: ${{ secrets.DBPASSWORD }}
        run: |
          echo "Deploying DB_USER: $DB_USER"
          if [[ "$DB_USER" == "mouser" ]]; then
              echo "DB user exists"
          if
          if [[ "$DB_HOST" == "TestPGServer" ]]; then
              echo "DB_HOST exists"
          if
          if [[ "$DB_Password" == "Test@123" ]]; then
              echo "DB DB_Password exists"
          if
          echo "Deploying DB_HOST: $DB_HOST"
          echo "Deploying DB_Password: $DB_Password"
          echo "Deploying DB_USER: " ${{ vars.DBUSERNAME }}
          echo "Deploying DB_HOST: " ${{ vars.SERVERNAME }}
          echo "Deploying scripts for database folder: $DB_NAME_INPUT"
          
