name: Demo Deploy Stanza Database Scripts
on:
  workflow_dispatch:
      inputs:
        environment:
            description: Environment to deploy to
            required: true
            type: environment
        dbName:
          description: 'Select the database folder to deploy'
          required: true
          type: choice
          options:
            - None
            - Committee
            - Identity
          default: None
permissions: read-all  

jobs:
  test-vars:
    runs-on: ubuntu-latest
    env:
      DUSER: ${{ vars.DBUSERNAME }}
      DHOST: ${{ vars.SERVERNAME }}
      DPASS: ${{ secrets.DBPASSWORD }}

    steps:
      - name: Print input and env variables
        run: |
         
          echo "==============================="
          echo "DB Folder Name: ${{ github.event.inputs.dbName }}"
          echo "DB_USER: $DUSER"
          echo "DB_HOST: $DHOST"
          echo "DB_PASSWORD: $DPASS"
          echo "==============================="
