name: Demo Deploy Stanza Database Scripts
on:
  workflow_dispatch:
      inputs:
        environment:
            description: Environment to deploy to
            required: true
            type: environment
        dbName:
          description: 'Select the database folder to deploy'
          required: true
          type: choice
          options:
            - None
            - Committee
            - Identity
          default: None
permissions: read-all  

jobs:
  DB_Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute database scripts filtered by DB folder name
        env:
          DB_NAME_INPUT: ${{ github.event.inputs.dbName }}
          DB_USER: ${{ vars.DBUSERNAME }}
          DB_HOST: ${{ vars.SERVERNAME }}
          
        run: |
          set -e
          echo "Deploying DB_USER: $DB_USER"
          echo "Deploying DB_HOST: $DB_HOST"
          echo "Deploying DB_HOST: " ${{ vars.DBUSERNAME }}
          echo "Deploying DB_HOST: " ${{ vars.SERVERNAME }}
          echo "Deploying scripts for database folder: $DB_NAME_INPUT"
          
